GAME_NAME = "Zegend of Lelda"

FPS = 60

DISPLAY_HEIGHT = 640
DISPLAY_WIDTH = 1024

GLOBAL_OBJECT_SIZE = 64

TILE_BUFFER = 1
HORIZONTAL_TILES_ON_CAMERA = round(DISPLAY_WIDTH / GLOBAL_OBJECT_SIZE + TILE_BUFFER)
VERTICAL_TILES_ON_CAMERA = round(DISPLAY_HEIGHT / GLOBAL_OBJECT_SIZE + TILE_BUFFER)

STARTING_X = DISPLAY_WIDTH / 2
STARTING_Y = DISPLAY_HEIGHT / 2
